version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  booking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
